export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const HISTORY_TOPUP = 'HISTORY_TOPUP';
export const HISTORY_TRANSACTION = 'HISTORY_TRANSACTION';
